import os
from unittest.mock import MagicMock
from atm.config.schema import GameProfile
from atm.core.deployment.game_deployer import GameDeployer

def test_deployer_preserves_and_restores_user_config(tmp_path):
    game_dir = tmp_path / 'UnityGame'
    game_dir.mkdir()
    exe_path = game_dir / 'Game.exe'
    exe_path.touch()

    bepinex_config = game_dir / 'BepInEx' / 'config'
    bepinex_config.mkdir(parents=True)
    ini_file = bepinex_config / 'AutoTranslatorConfig.ini'

    original_content = "[Service]\nUnaffectedOpt=1 2 3\n\n[Behaviour]\nMinDialogueChars=99\nCustomSetting=UserValue\n"
    ini_file.write_text(original_content, encoding='utf-8')

    profile = GameProfile(
        game_name='UnityGame',
        exe_path=str(exe_path),
        engine='Unity Mono',
        translator='google',
        input_lang='ja',
        output_lang='vi'
    )

    deployer = GameDeployer()
    deployer.monitor = MagicMock()
    deployer.monitor.start_and_monitor.return_value = True

    deployer.deploy_and_launch(profile, payload_dir='')

    backup_file = str(ini_file) + '.atm_backup'
    assert os.path.exists(backup_file)

    merged_content = ini_file.read_text(encoding='utf-8')
    assert 'Endpoint=CustomTranslate' in merged_content
    assert 'MinDialogueChars=99' in merged_content
    assert 'CustomSetting=UserValue' in merged_content

    deployer._on_game_exited()

    assert not os.path.exists(backup_file)
    assert ini_file.exists()
    restored_content = ini_file.read_text(encoding='utf-8')
    assert restored_content == original_content

def test_deployer_cleans_up_newly_created_config(tmp_path):
    game_dir = tmp_path / 'UnityGameClean'
    game_dir.mkdir()
    exe_path = game_dir / 'Game.exe'
    exe_path.touch()

    profile = GameProfile(
        game_name='UnityGameClean',
        exe_path=str(exe_path),
        engine='Unity Mono',
        translator='google',
        input_lang='ja',
        output_lang='vi'
    )

    deployer = GameDeployer()
    deployer.monitor = MagicMock()
    deployer.monitor.start_and_monitor.return_value = True

    deployer.deploy_and_launch(profile, payload_dir='')

    ini_file = game_dir / 'BepInEx' / 'config' / 'AutoTranslatorConfig.ini'
    assert ini_file.exists()

    deployer._on_game_exited()
    assert not ini_file.exists()

def test_deployer_preserves_and_merges_pre_existing_disk_translations(tmp_path):
    game_dir = tmp_path / 'UnityGameWithTrans'
    game_dir.mkdir()
    exe_path = game_dir / 'Game.exe'
    exe_path.touch()

    trans_dir = game_dir / 'BepInEx' / 'Translation' / 'vi' / 'Text'
    trans_dir.mkdir(parents=True)
    trans_file = trans_dir / '_AutoGeneratedTranslations.txt'
    trans_file.write_text("OldKey=OldValue\nAnotherKey=AnotherValue\n", encoding='utf-8-sig')

    profile = GameProfile(
        game_name='UnityGameWithTrans',
        exe_path=str(exe_path),
        engine='Unity Mono',
        translator='google',
        input_lang='ja',
        output_lang='vi'
    )

    from atm.storage.repositories.translation_repository import TRANSLATIONS_DIR
    from atm.storage.repositories.sqlite_game_lines import SQLiteGameLinesRepository
    gl_repo = SQLiteGameLinesRepository(os.path.join(TRANSLATIONS_DIR, "translation_cache.db"))
    gl_repo.batch_insert(profile.id, [{"original": "NewKey", "translated": "NewValue", "source_file": "test_source"}])

    deployer = GameDeployer()
    deployer.monitor = MagicMock()
    deployer.monitor.start_and_monitor.return_value = True

    deployer.deploy_and_launch(profile, payload_dir='')

    merged_text = trans_file.read_text(encoding='utf-8-sig')
    assert "OldKey=OldValue" in merged_text
    assert "AnotherKey=AnotherValue" in merged_text
    assert "NewKey=NewValue" in merged_text

    deployer._on_game_exited()
    # Ensure pre-existing translations file is kept on disk
    assert trans_file.exists()

